name: continuous-integration
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Docker image
      run: docker build -t mnaiem262/demo_kotlin_gradle:1.1 .
    - name: Push Docker image
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker push mnaiem262/demo_kotlin_gradle:1.1 